import React from "react";
import image5 from "../assets/projectimages/Rectangle1copie2.png";
import image6 from "../assets/projectimages/Rectangle1copie5.png";

import image15 from "../assets/projectimages/Ligne1.png";
import image16 from "../assets/projectimages/Ligne1_0.png";
import image17 from "../assets/projectimages/Ligne1_1.png";
import image18 from "../assets/projectimages/Ligne1_2.png";

import image26 from "../assets/projectimages/Rectangle1copie6.png";
import image28 from "../assets/projectimages/ChangeyourBNBoryourU.png";
import image29 from "../assets/projectimages/Allticketssell.png";
import image32 from "../assets/projectimages/BSCSmartcontractpick.png";
import image33 from "../assets/projectimages/Winnerscanclaimedthe.png";
import image34 from "../assets/projectimages/Winnersclaimedtheirr.png";
import image35 from "../assets/projectimages/PlayinFUNC.png";
import image36 from "../assets/projectimages/Rectangle1copie8.png";
import image38 from "../assets/projectimages/Rectangle1copie9.png";
import image40 from "../assets/projectimages/Rectangle1copie10.png";
import image42 from "../assets/projectimages/Rectangle1copie11.png";
import image44 from "../assets/projectimages/Rectangle1copie7.png";
import image54 from "../assets/projectimages/Ligne2.png";
import image55 from "../assets/projectimages/Objetdynamiquevector_1.png";
import image56 from "../assets/projectimages/line.png";
import image68 from "../assets/projectimages/pt10.png";
import image69 from "../assets/projectimages/SeedQ42020.png";
import image70 from "../assets/projectimages/PrelaunchQ12021.png";
import image71 from "../assets/projectimages/FunCouponsresearchan.png";
import image72 from "../assets/projectimages/DevelopmentQ42021.png";
import image73 from "../assets/projectimages/FUNClistingsLaunchin.png";
import image74 from "../assets/projectimages/TestQ22021.png";
import image75 from "../assets/projectimages/TestnetlaunchStartin.png";
import image76 from "../assets/projectimages/BuildinguptheteamAct.png";
import image77 from "../assets/projectimages/LaunchQ32021.png";
import image78 from "../assets/projectimages/WebsitelaunchLaunchi.png";

import image81 from "../assets/projectimages/Ligne3.png";
import image82 from "../assets/projectimages/Triangle1.png";
import image83 from "../assets/projectimages/Triangle1_0.png";
import image84 from "../assets/projectimages/Triangle1copie21.png";
import image85 from "../assets/projectimages/Triangle1copie21_0.png";
import image86 from "../assets/projectimages/Triangle1copie21_1.png";
import image87 from "../assets/projectimages/Groupe3copie.png";
import image88 from "../assets/projectimages/Groupe3copie_0.png";
import image89 from "../assets/projectimages/Ligne4.png";
import image90 from "../assets/projectimages/Ligne4copie.png";
import image91 from "../assets/projectimages/Ligne4copie2.png";
import image92 from "../assets/projectimages/Ligne5.png";
import image93 from "../assets/projectimages/Ligne6.png";
import image94 from "../assets/projectimages/Ligne7.png";
import imagept1 from "../assets/projectimages/pt1.png";
import imagept3 from "../assets/projectimages/pt3.png";
import imagept5 from "../assets/projectimages/pt5.png";
import imagept7 from "../assets/projectimages/pt7.png";

import "./project.css";

export default function Project() {
  //background-image: linear-gradient(#07042E, #000059)
  return (
    <div id="backgroundProject">
      <div id="Rectangle1">
        {/* <img src={image1} alt="secondaryimage" /> */}
      </div>
      <div id="Rectangle1copie3">
        {/* <img src={image2} alt="secondaryimage" /> */}
      </div>
      <div id="Rectangle1copie4">
        {/* <img src={image3} alt="secondaryimage" /> */}
      </div>
      <div id="Rectangle1copie">
        {/* <img src={image4} alt="secondaryimage" /> */}
      </div>
      <div id="Rectangle1copie2">
        <img src={image5} alt="secondaryimage" />
      </div>
      <div id="Rectangle1copie5">
        <img src={image6} alt="secondaryimage" />
      </div>
      <div id="HighHouseEdgeCostsac">
        <span style={{ color: "#f85100", fontSize: "12px" }}>
          High House Edge Costs:{" "}
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          according to reports, 37% to 50% of the money generated by the lottery
          is used by jurisdictions, companies or game design. However, lower
          costs could increase the prizes.
        </span>
      </div>
      <div id="HighHouseEdgecostswi">
        <span style={{ color: "#b56d93", fontSize: "12px" }}>
          High House Edge Costs:{" "}
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          {" "}
          with less fees than a traditional gaming company, Fun Coupons can
          increase the number of winners with lower margins.
        </span>
      </div>
      <div id="Identificationplayer">
        <span style={{ color: "#f85100", fontSize: "12px" }}>
          Identification
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          players have to prove their ID to participate or to cash out their
          prize. Without a correct and thorough check, the winning tickets can
          be lost or destroyed.
        </span>
      </div>
      <div id="Identificationplayer_0">
        <span style={{ color: "#b56d93", fontSize: "12px" }}>
          Identification
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          {" "}
          players can access to the game easily with any crypto wallets and get
          their prize instantly from the blockchain. With the BSC, the
          transactions have ultra low fees and are much faster.
        </span>
      </div>
      <div id="TransparencyFairness">
        <span style={{ color: "#f85100", fontSize: "12px" }}>
          Transparency & Fairness:
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          random number generator (R.N.G) is rarely public and can be rigged.
        </span>
      </div>
      <div id="TransparencyFairness_0">
        <span style={{ color: "#b56d93", fontSize: "12px" }}>
          Transparency & Fairness:
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          {" "}
          when hosting by Smart Contracts, the games, rules and processes can be
          audited by anybody.
        </span>
      </div>
      <div id="Securitycentraliseds">
        <span style={{ color: "#f85100", fontSize: "12px" }}>Security:</span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          centralised servers that can be hacked.
        </span>
      </div>
      <div id="Securitywiththeblock">
        <span style={{ color: "#b56d93", fontSize: "12px" }}>Security:</span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          with the blockchain approach all information and processes are
          controlled and decentralized.
        </span>
      </div>
      <div id="Ligne1">
        <img src={image15} alt="secondaryimage" />
      </div>
      <div id="Ligne1_0">
        <img src={image16} alt="secondaryimage" />
      </div>
      <div id="Ligne1_1">
        <img src={image17} alt="secondaryimage" />
      </div>
      <div id="Ligne1_2">
        <img src={image18} alt="secondaryimage" />
      </div>
      <div id="FUNCOUPONSPitch">
        <p style={{ color: "hsl(173deg 88% 66%)", fontSize: "20px" }}>
          FUN COUPONS PITCH
        </p>
      </div>
      <div id="Introduction">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>Introduction</span>
      </div>
      <div id="TraditionalvsFunCoup">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>
          Traditional vs Fun Coupons Lotteries
        </span>
      </div>
      <div id="Insteadofcreatingacl">
        <span>
          Instead of creating a classic lottery with only one winner and no sale
          tickets limit, Fun Coupons defines a number of tickets to be sold per
          lottery from the beginning. The aim is to increase the chances of
          winning for all participants. The tickets always represents 120% of
          the jackpot amount.
          <br />
          <br />
        </span>
        <span>
          The lottery beginnings only when all tickets are sold out.
          <br />
          <br />
        </span>
        <span>
          When one lottery is done, no matter the amount, a new lottery with the
          same award amount will be begin.
          <br />
        </span>
      </div>
      <div id="HowtheFunCouponsLott">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>
          How the Fun Coupons Lotteries Works?
        </span>
      </div>
      <div id="DiscoveringtheFunCou">
        <span style={{ color: "#fff", fontSize: "12px" }}>
          Discovering the Fun Coupons platform should be effortless, intuitive,{" "}
          <br />
          and most importantly fun for the player. <br /> <br />
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          To increase the fun, we are looking into expanding our features soon:
          <br />
          <br />
        </span>
        <span style={{ color: "#8f86e9", fontSize: "12px" }}>
          Bigger jackpots
          <br />
          No loss lotteries
          <br />
          New games <br />
          <br />
          <br />
        </span>
      </div>
      <div id="ExpandFun">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>Expand Fun</span>
      </div>
      <div id="Roadmap">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>Roadmap</span>
      </div>
      <div id="Project4thto10th18toshare10">
        <span style={{ fontSize: "11px" }}>
          4th to10th: 18% to share
          <br />
        </span>
        <span style={{ fontSize: "11px" }}>
          10th to 20th: 6% to share
          <br />
        </span>
        <span style={{ fontSize: "11px" }}>
          20th to 35th: 7% to share
          <br />
        </span>
        <span style={{ fontSize: "11px" }}>
          35th to 50th: 4% to share
          <br />
        </span>
      </div>
      <div id="Project1stWinner502ndWinner">
        <span style={{ fontSize: "16px" }}>
          1st Winner: 50%
          <br />
        </span>
        <span style={{ fontSize: "16px" }}>
          2nd Winner: 10%
          <br />
        </span>
        <span style={{ fontSize: "16px" }}>
          3rd Winner: 5%
          <br />
        </span>
      </div>
      <div id="Thejackpotdividing">
        <span style={{ fontSize: "11px" }}>The jackpot dividing:</span>
      </div>
      <div id="Objetdynamiquevector_1Project">
        <img src={image55} alt="secondaryimage" />
      </div>

      <div id="DistributionLotterie">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>
          Distribution Lotteries
        </span>
      </div>
      <div id="LotteryMechanismOver">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>
          Lottery Mechanism Overview
        </span>
      </div>
      <div id="FunCouponsisthenextg">
        <span style={{ color: "white", textAlign: "center", fontSize: "12px" }}>
          Fun Coupons is the next generation of lottery platforms.
          <br />
          <br />
          <br />
        </span>
        <span style={{ color: "white", fontSize: "12px", textAlign: "center" }}>
          With the Binance Smart Chain blockchain features we create equity{" "}
          <br />
          cryptocurrency lotteries in a transparent and decentralized way.
        </span>
      </div>
      <div id="HighChanceLotteries">
        <span style={{ fontSize: "12px" }}>High Chance Lotteries</span>
      </div>
      <div id="DecentralizedTrustwo">
        <span style={{ fontSize: "12px" }}>
          Decentralized & Trustworthy Games
        </span>
      </div>
      <div id="Experience">
        <span>Experience</span>
      </div>
      <div id="Rectangle1copie6">
        <img src={image26} alt="secondaryimage" />
      </div>
      <div id="YourMetamaskWallet">
        <span style={{ color: "#01cd8b", fontSize: "12px" }}>
          Your Metamask Wallet
        </span>
      </div>
      <div id="ChangeyourBNBoryourU">
        <img src={image28} alt="secondaryimage" />
      </div>
      <div id="Allticketssell">
        <img src={image29} alt="secondaryimage" />
      </div>
      <div id="BSCSmartcontractpick">
        <img src={image32} alt="secondaryimage" />
      </div>
      <div id="Winnerscanclaimedthe">
        <img src={image33} alt="secondaryimage" />
      </div>
      <div id="Winnersclaimedtheirr">
        <img src={image34} alt="secondaryimage" />
      </div>
      <div id="PlayinFUNC">
        <img src={image35} alt="secondaryimage" />
      </div>
      <div id="Rectangle1copie8">
        <img src={image36} alt="secondaryimage" />
      </div>
      <div id="FUNCLotteriesBSCBloc">
        <span style={{ color: "#fe4c8f", fontSize: "12px" }}>
          FUNC Lotteries BSC Blockchain
        </span>
      </div>
      <div id="Rectangle1copie9">
        <img src={image38} alt="secondaryimage" />
      </div>
      <div id="LotteryFinished">
        <span style={{ color: "#01cd8b", fontSize: "12px" }}>
          Lottery Finished
        </span>
      </div>
      <div id="Rectangle1copie10">
        <img src={image40} alt="secondaryimage" />
      </div>
      <div id="WinnersDeclared">
        <span style={{ color: "#897531", fontSize: "12px" }}>
          Winners Declared
        </span>
      </div>
      <div id="Rectangle1copie11">
        <img src={image42} alt="secondaryimage" />
      </div>
      <div id="Winnersreceivetheirp">
        <span style={{ color: "#905e8b", fontSize: "12px" }}>
          Winners Recieve Their Prizes
        </span>
      </div>
      <div id="Rectangle1copie7">
        <img src={image44} alt="secondaryimage" />
      </div>
      <div id="FunCouponsExchange">
        <span style={{ color: "#943c2a", fontSize: "12px" }}>
          Fun Coupons Exchange
        </span>
      </div>
      <div id="HighPerformanceLowFe">
        <span style={{ fontSize: "12px" }}>High Performance Low Fees</span>
      </div>
      <div id="VotingToken">
        <span style={{ fontSize: "12px" }}>Voting Token</span>
      </div>
      <div id="EcoFriendly">
        <span style={{ fontSize: "12px" }}>Eco Friendly</span>
      </div>
      <div id="HighChanceLotteriesU">
        <span style={{ color: "#3fe7b3", fontSize: "12px" }}>
          High Chance Lotteries
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          Unlike the classic Lottery, Fun Coupons defines the number of tickets
          for each lottery in order to control the winners percentage. We ensure
          that 50% of the tickets are winning tickets. There are also different
          lotteries with different opportunities to win the first prize.
          <br />
          <br />
        </span>

        <span style={{ color: "#3fe7b3", fontSize: "12px" }}>
          Decentralized & Trustworthy Games
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          The BSC hosts the database that guarantees untampered access to all
          lottery processes and algorithm. Meaning, all users can audit the
          transactions if they desire.
          <br />
          <br />
        </span>

        <span style={{ color: "#3fe7b3", fontSize: "12px" }}>
          Experience
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          The platform offers a simple and intuitive experience. Fun Coupons
          allows anyone to participate easily in any crypto lottery. We, as the
          experts, also suggest various lotteries to join.
          <br />
          <br />
        </span>

        <span style={{ color: "#3fe7b3", fontSize: "12px" }}>
          High Performance & Low Fees
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          Binance Smart Chain allows Lovely Coin to perform transactions in an
          ultra-fast and secure environment while maintaining limited fee
          exposure for our end-users.
          <br />
          <br />
        </span>

        <span style={{ color: "#3fe7b3", fontSize: "12px" }}>
          Voting Toking
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          The Fun Coupons stakeholders will be able to submit proposals, vote on
          initiatives, create new lottery, and moderate the platform to ensure
          alignment with evolving needs of the community.
          <br />
          <br />
        </span>
        <span style={{ color: "#3fe7b3", fontSize: "12px" }}>
          Eco-Friendly
          <br />
        </span>
        <span style={{ color: "#fff", fontSize: "12px" }}>
          BSC's consensus mechanism (a hybrid of dPoS and PoA) is designed to be
          more efficient and environmentally friendly than Ethereum's PoW.
        </span>
      </div>
      <div id="FunCouponsFeatures">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>
          Fun Coupons Features
        </span>
      </div>
      <div id="FunCouponsOverview">
        <span style={{ color: "#a821ff", fontSize: "20px" }}>
          Fun Coupons Overview
        </span>
      </div>
      <div id="TraditionalOnlineLot">
        <span style={{ color: "#f85100", fontSize: "18px" }}>
          Traditional Online Lottery Issues
        </span>
      </div>
      <div id="FunCouponsSolution">
        <span style={{ color: "#b56d93", fontSize: "18px" }}>
          Fun Coupons Solution
        </span>
      </div>
      <div id="Ligne2">
        <img src={image54} alt="secondaryimage" />
      </div>
      <div id="line">
        <img src={image56} alt="secondaryimage" />
      </div>
      <div id="pt1">
        <img src={imagept1} alt="secondaryimage" />
      </div>
      <div id="pt3">
        <img src={imagept3} alt="secondaryimage" />
      </div>
      <div id="pt5">
        <img src={imagept5} alt="secondaryimage" />
      </div>
      <div id="pt7">
        <img src={imagept7} alt="secondaryimage" />
      </div>
      <div id="pt10">
        <img src={image68} alt="secondaryimage" />
      </div>
      <div id="SeedQ42020">
        <img src={image69} alt="secondaryimage" />
      </div>
      <div id="PrelaunchQ12021">
        <img src={image70} alt="secondaryimage" />
      </div>
      <div id="FunCouponsresearchan">
        <img src={image71} alt="secondaryimage" />
      </div>
      <div id="DevelopmentQ42021">
        <img src={image72} alt="secondaryimage" />
      </div>
      <div id="FUNClistingsLaunchin">
        <img src={image73} alt="secondaryimage" />
      </div>
      <div id="TestQ22021">
        <img src={image74} alt="secondaryimage" />
      </div>
      <div id="TestnetlaunchStartin">
        <img src={image75} alt="secondaryimage" />
      </div>
      <div id="BuildinguptheteamAct">
        <img src={image76} alt="secondaryimage" />
      </div>
      <div id="LaunchQ32021">
        <img src={image77} alt="secondaryimage" />
      </div>
      <div id="WebsitelaunchLaunchi">
        <img src={image78} alt="secondaryimage" />
      </div>
      {/* <div id="Rectangle2Project">
        <img src={image79} alt="secondaryimage" />
      </div>
      <div id="Rectangle2copieProject">
        <img src={image80} alt="secondaryimage" />
      </div> */}
      <div id="Ligne3">
        <img src={image81} alt="secondaryimage" />
      </div>
      <div id="Triangle1">
        <img src={image82} alt="secondaryimage" />
      </div>
      <div id="Triangle1_0">
        <img src={image83} alt="secondaryimage" />
      </div>
      <div id="Triangle1copie21">
        <img src={image84} alt="secondaryimage" />
      </div>
      <div id="Triangle1copie21_0">
        <img src={image85} alt="secondaryimage" />
      </div>
      <div id="Triangle1copie21_1">
        <img src={image86} alt="secondaryimage" />
      </div>
      <div id="Groupe3copie">
        <img src={image87} alt="secondaryimage" />
      </div>
      <div id="Groupe3copie_0">
        <img src={image88} alt="secondaryimage" />
      </div>
      <div id="Ligne4">
        <img src={image89} alt="secondaryimage" />
      </div>
      <div id="Ligne4copie">
        <img src={image90} alt="secondaryimage" />
      </div>
      <div id="Ligne4copie2">
        <img src={image91} alt="secondaryimage" />
      </div>
      <div id="Ligne5">
        <img src={image92} alt="secondaryimage" />
      </div>
      <div id="Ligne6">
        <img src={image93} alt="secondaryimage" />
      </div>
      <div id="Ligne7">
        <img src={image94} alt="secondaryimage" />
      </div>
    </div>
  );
}
